[package]
name = "hildie_bindings"
version = "0.1.0"
edition = "2021"

[lib]
name = "hildie_bindings"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }

[dependencies.hildie-lib]
path = "../rust/hildie-lib"
