[package]
name = "hildie-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "hildie-cli"
path = "src/main.rs"

[dependencies]
hildie-lib = { path = "../hildie-lib" }
